# Generated by Django 4.0.2 on 2023-06-02 22:22

import base.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarterUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(default=base.models.rand_code, editable=False, max_length=20, verbose_name='Código')),
                ('birthdate', models.DateTimeField(verbose_name='birthdate')),
                ('first_name', models.CharField(max_length=20, verbose_name='first name')),
                ('last_name', models.CharField(max_length=20, verbose_name='last name')),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=10, null=True, verbose_name='RG')),
                ('gender', models.CharField(blank=True, choices=[('m', 'male'), ('f', 'female'), ('o', 'other')], max_length=1, null=True, verbose_name='gender')),
                ('user_type', models.CharField(choices=[('COMPANY', 'company'), ('ADMIN', 'adminstrator'), ('SELLER', 'seller')], max_length=10, verbose_name='user type')),
                ('profile_img', models.URLField(blank=True, null=True, verbose_name='profile image')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.address')),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.contact')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carter_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carter User',
                'verbose_name_plural': 'Carter Users',
            },
        ),
    ]
