# Generated by Django 4.0.2 on 2023-06-03 01:31

import base.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(default=base.models.rand_code, editable=False, max_length=20, verbose_name='Código')),
                ('cnpj', models.CharField(max_length=16, verbose_name='CNPJ')),
                ('fantasy_name', models.CharField(max_length=50, verbose_name='fantasy name')),
                ('corporate_name', models.CharField(max_length=50, verbose_name='corporate name')),
                ('company_logo', models.URLField(blank=True, null=True, verbose_name='company logo')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.address')),
                ('carter_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_user', to='authentication.carteruser')),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.contact')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
