# Generated by Django 4.0.2 on 2023-06-02 22:22

import base.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(default=base.models.rand_code, editable=False, max_length=20, verbose_name='Código')),
                ('address_type', models.CharField(choices=[('HOME', 'home address'), ('BUSINESS', 'business address'), ('TEMP', 'temporary address')], max_length=9, verbose_name='address type')),
                ('street', models.CharField(max_length=50, verbose_name='street')),
                ('neighborhood', models.CharField(max_length=30, verbose_name='neighborhood')),
                ('number', models.CharField(max_length=6, verbose_name='number')),
                ('zip_code', models.CharField(max_length=7, verbose_name='zip code')),
                ('city', models.CharField(max_length=30, verbose_name='city')),
                ('state', models.CharField(max_length=4, verbose_name='state')),
                ('country', models.CharField(max_length=20, verbose_name='country')),
                ('complement', models.CharField(blank=True, max_length=100, null=True, verbose_name='complement')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(default=base.models.rand_code, editable=False, max_length=20, verbose_name='Código')),
                ('phone', models.CharField(max_length=12, verbose_name='phone')),
                ('seccond_phone', models.CharField(max_length=12, verbose_name='phone')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('linkedIn', models.URLField(blank=True, null=True, verbose_name='LinkdIn')),
                ('site', models.URLField(blank=True, null=True, verbose_name='site')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
